settings:
  username: "thoemmi"
  max_lines: 5
  readme_file: "./README.md"
  whitelisted_events:
    - "push"
    - "issues"
    - "pr"
    - "review"
    - "release"
  ignored_repos:
    - "thoemmi/thoemmi"
  commit_msg: "chore: update recent GitHub activity"
  commit_name: "github-actions[bot]"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
